spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_shop_clothes}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: shop_clothes
server:
  port: 8082

dropbox:
  access:
    token: sl.B6relLsxr0jsJYxmQK5zt3HHYEfSe1A-PSmyy4u83VDvLASRPE-eEIf9j3n8pwe-mClPiKu5MscBSYzWAY-_bd5GdThEb5iLBYhLpBWSVLAnsKS1ptn6iFXwG536wkiVK4SwkVR0vrjlX4g